bin.includes = META-INF/,\
               .,\
               plugin.xml,\
               Application.e4xmi
source.. = src/
output.. = bin/
src.includes = Application.e4xmi
jre.compilation.profile = JavaSE-25
